#!/bin/sh

if [ $# -ne 0 ] ; then
    echo "Usage: generate-headers" 1>&2
    exit 1
fi
name="$1"

for nc in {2,3} ; do
  echo generating Nc=$nc
  utils/prebuild $nc
  cp port/qop-clover.h nc/qop-clover$nc.h
done
