#!/bin/sh -f

#targets="bgq/xlc c99-32 c99-64 cee-32 cee-64"
targets="bgq/xlc cee-64"

set -e
make -C noweb
make -C noweb clean
make -C qa0 TARGETS="$targets"
version=`basename $PWD`
tar -cf - -C .. $version | bzip2 -9 > ../$version.tar.bz2
